# Évolution par continent


```{r, include=FALSE}
consommation_energie <- read_delim("owid-energy-data__OWID.csv") |> 
  select(iso_code, country, year, matches("_consu")) |> 
  filter(year >= 1950) |> 
  mutate_at(c(4:16), ~replace_na(.,0)) |> 
  mutate(year=as_factor(year))





production_alimentaire <- read_delim("Production_Crops_Livestock_E_All_Data.csv") |> 
  filter(str_detect(Item, "otal")) |> 
  select("Area Code", Area, "Item Code", Item, "Element Code", Element, Unit, matches("Y[0-9]{4}$")) |> 
  pivot_longer(cols=8:67,
               names_to="year",
               values_to="valeur") |> 
  mutate(year=str_remove(year, "Y")) |> 
  mutate(valeur=replace(valeur, is.na(valeur), 0)) |> 
  mutate(year=as_factor(year))



# Population

population <- read_delim("WPP2019_POP_F01_1_TOTAL_POPULATION_BOTH_SEXES_UN.csv") |> 
  select(-Variant) |> 
  pivot_longer(cols=7:77,
               names_to="year",
               values_to="population") |> 
  rename(region=2) |> 
  mutate(year=as_factor(year)) |> 
  mutate(population=str_remove_all(population, " ")) |> 
  mutate(population=as.integer(population)*1000)





# Tables des codes et noms des pays

codes_pays <- consommation_energie |> 
  select(iso_code, country) |> 
  distinct(iso_code, country)



liste_continents <- read_delim("country-and-continent-codes-list.csv", delim=",") |> 
  select(-Country_Name) |> 
  rename(continent=Continent_Name) |> 
  rename(iso_code=Three_Letter_Country_Code)


```

-----------------------------------------------------------------------

## Consommation totale d'énergie par continent

```{r, echo=FALSE}
consommation_energie_continent <- consommation_energie |> 
  left_join(liste_continents) |> 
  group_by(continent, year) |> 
  summarize(renouvelable=sum(renewables_consumption),
            non_renouvelable=sum(fossil_fuel_consumption)) |> 
  pivot_longer(cols=renouvelable:non_renouvelable,
               names_to="type",
               values_to="valeur")

conso <- consommation_energie |> 
  mutate(iso_code2=iso_code) |> 
  full_join(liste_continents) |>  
  distinct(iso_code, iso_code2)

ggplot(consommation_energie_continent)+
  aes(x=year,
      y=valeur,
      fill=continent)+
  scale_x_discrete(breaks=seq(1950, 2020, 10))+
  geom_col()
```

-----------------------------------------------------------------------

## Production alimentaire totale par continent

```{r, echo=FALSE}
production_alimentaire_continents <- production_alimentaire |> 
  rename(country=Area) |> 
  left_join(codes_pays) |> 
  left_join(liste_continents) |> 
  group_by(continent, year, Item) |> 
  summarize(somme=sum(valeur))



# energy_countrycode<-energy |> mutate(iso_code2=countrycode(country, origin = “country.name”, destination = “iso3c”))

ggplot(production_alimentaire_continents)+
  aes(x=year,
      y=somme,
      fill=continent)+
  scale_x_discrete(breaks=seq(1950, 2020, 10))+
  geom_col()
```

## Évolution de la population par continent

```{r, echo=FALSE}
population_continent <- population |> 
  filter(Type=="Region") |> 
  group_by(region)


ggplot(population_continent)+
  aes(x=year,
      y=population,
      fill=region)+
  scale_x_discrete(breaks=seq(1950, 2020, 10))+
  geom_col()
```